Repository citizensadvice/design-system, pull requests merged in 2020-09, with the labels that each got.

#207 feature: Enable Browserstack [NP-765]
  .editorconfig
  Jenkinsfile
  testing/cucumber.yml
Labels: do not merge

#209 feature: automated accessibility testing setup [NP-382]
  CHANGELOG.md
  CONTRIBUTING.md
  package.json
  scripts/update-pa11y-config.js
  scripts/wcag-test.js
  styleguide/haml_locals.rb
  testing/package-lock.json
  testing/package.json
  testing/wcag/.pa11yci.ci.json
  testing/wcag/.pa11yci.local.json
Labels: dev review needed

#219 fix: navigation spacing [NP-816]
  CHANGELOG.md
  docker-compose.yml
  scripts/vr-test.js
  scss/6-components/_navigation.scss
  testing/visual-regression/backstop-ci.json
  testing/visual-regression/backstop.json
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_NAVIGATION_BUTTONS_0_document_0_phone.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_NAVIGATION_BUTTONS_0_document_1_Small.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_NAVIGATION_BUTTONS_0_document_2_Medium.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_NAVIGATION_BUTTONS_0_document_3_Large.png
Labels: design review needed, qa review needed

#243 Feature: reconcile search with designs [NP-895]
  .stylelintrc.json
  CHANGELOG.md
  haml/_footer.html.haml
  haml/_search.html.haml
  scss/6-components/_footer.scss
  scss/6-components/_header.scss
  scss/6-components/_navigation.scss
  scss/6-components/_search.scss
  testing/visual-regression/backstop-common.js
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_HEADER_0_a11yComponentToTest_2_Medium.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_HEADER_0_a11yComponentToTest_3_Large.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_HEADER_EXPANDED_0_a11yComponentToTest_0_phone.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_SEARCH_0_a11yComponentToTest_0_phone.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_SEARCH_0_a11yComponentToTest_1_Small.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_SEARCH_0_a11yComponentToTest_2_Medium.png
  testing/visual-regression/backstop_data/bitmaps_reference/backstop_default_3_Components_SEARCH_0_a11yComponentToTest_3_Large.png
Labels: qa review needed
